// patients
export const FETCH_PATIENTS_REQUEST = 'FETCH_PATIENTS_REQUEST';
export const FETCH_PATIENTS_FAILURE = 'FETCH_PATIENTS_FAILURE';
export const FETCH_PATIENTS_SUCCESS = 'FETCH_PATIENTS_SUCCESS';

export const DELETE_PATIENT_REQUEST = 'DELETE_PATIENT_REQUEST';
export const DELETE_PATIENT_FAILURE = 'DELETE_PATIENT_FAILURE';
export const DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_SUCCESS';

export const ADD_PATIENT_REQUEST = 'ADD_PATIENT_REQUEST';
export const ADD_PATIENT_FAILURE = 'ADD_PATIENT_FAILURE';
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';

export const UPDATE_PATIENT_REQUEST = 'UPDATE_PATIENT_REQUEST';
export const UPDATE_PATIENT_FAILURE = 'UPDATE_PATIENT_FAILURE';
export const UPDATE_PATIENT_SUCCESS = 'UPDATE_PATIENT_SUCCESS';

// patientForm
export const SET_PATIENT = 'SET_PATIENT';
export const UNSET_PATIENT = 'UNSET_PATIENT';
export const ADD_PATIENT_DIAPER = 'ADD_PATIENT_DIAPER';
export const REMOVE_PATIENT_DIAPER = 'REMOVE_PATIENT_DIAPER';
export const UPDATE_PATIENT_FIELD = 'UPDATE_PATIENT_FIELD';
export const UPDATE_PATIENT_DIAPER_FIELD = 'UPDATE_PATIENT_DIAPER_FIELD';
